### ISSUE TITLE
testeth error message should be more informative when filler JSON expect contains int

### ISSUE THREAD

**Issue by lrettig** [ethereum/cpp-ethereum#4889]
Cf. #4211 

For some reason a filler file containing this section is still giving me a cryptic error:

```
   expect:
     - indexes:
         data: -1
         gas: -1
         value: -1
       network:
         - ALL
```

Adding `!!int` as below makes the error go away:

```
   expect:
     - indexes:
         data: !!int -1
         gas: !!int -1
         value: !!int -1
       network:
         - ALL
```

Here is the cryptic error I get:

`unknown location:0: fatal error: in "GeneralStateTests/stEWASMTests": std::runtime_error: value type is 2 not 4`
